In [2]:
import numpy as np


In [7]:
arr = np.array([1,2,3])
print(arr)
arr

[1 2 3]


array([1, 2, 3])

In [9]:
arr_1 = np.array([[2,4,6],[1,3,5]])
print(arr_1)

[[2 4 6]
 [1 3 5]]


In [59]:
ar = np.arange(1,11)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
ar0 = ar.reshape(2,5)
ar0

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

## Reshaping an array

In [10]:
arr11 = np.arange(100).reshape(10,10)
arr11

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [18]:
arr11 = np.arange(100).reshape(10,-5)
arr11

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
ind_state = np.array(['AP','MP','UP','KA','TN','GU','JK','HP','WB','MH','RJ','KL'])
ind_state

array(['AP', 'MP', 'UP', 'KA', 'TN', 'GU', 'JK', 'HP', 'WB', 'MH', 'RJ',
       'KL'], dtype='<U2')

In [20]:
ind_state.reshape(4,-1)

array([['AP', 'MP', 'UP'],
       ['KA', 'TN', 'GU'],
       ['JK', 'HP', 'WB'],
       ['MH', 'RJ', 'KL']], dtype='<U2')

## Transpose



In [22]:
# Transpose of matrix - rows and columns are interchanged
ind_state.reshape(4,-1).T


array([['AP', 'KA', 'JK', 'MH'],
       ['MP', 'TN', 'HP', 'RJ'],
       ['UP', 'GU', 'WB', 'KL']], dtype='<U2')

### Row  Measure and Column Measure

In [23]:
# row measure Format

np.reshape(ind_state,(4,-1),order = 'C')

array([['AP', 'MP', 'UP'],
       ['KA', 'TN', 'GU'],
       ['JK', 'HP', 'WB'],
       ['MH', 'RJ', 'KL']], dtype='<U2')

In [24]:
#  column measure format
np.reshape(ind_state,(4,-1),order = 'F')

array([['AP', 'TN', 'WB'],
       ['MP', 'GU', 'MH'],
       ['UP', 'JK', 'RJ'],
       ['KA', 'HP', 'KL']], dtype='<U2')

## Basic opearation on  array

In [27]:
arr1 = np.array([10,20,30,40])
# Adding a scalar quantity into an array

arr1+2

#Subtracting a scalar quantity from elements in an array

arr1-4

# Multiply
arr1 *5 

# Diving
arr1 /2
#raising power
arr1**3

#comparision operator - returns a boolean value
arr1<30

array([ True,  True, False, False])

In [30]:
ar1 = np.array([10,11,12,12]).reshape(2,2)
ar1

array([[10, 11],
       [12, 12]])

In [32]:
ar2 = np.array([20,21,22,23]).reshape(2,2)
ar2

array([[20, 21],
       [22, 23]])

In [33]:
# dot product
np.dot(ar1,ar2)

array([[442, 463],
       [504, 528]])

In [34]:
# otherway of writing dot product
ar1.dot(ar2)

array([[442, 463],
       [504, 528]])

In [36]:
ary = ar1*ar2
ary

array([[200, 231],
       [264, 276]])

In [41]:
ar1 += ar2
ar1

array([[50, 53],
       [56, 58]])

## Unary operations on array

In [43]:
# Aggregate functions - sum,min,max

print(np.max(ar1))
print(np.min(ar1))
np.sum(ar1)

58
50


217

In [45]:
arr3 = np.arange(25,50).reshape(5,-1)
arr3

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [49]:
print('row sum',np.sum(arr3, axis = 1))  # row sum 
print('column sum',np.sum(arr3, axis  = 0))         # column sum

row sum [135 160 185 210 235]
column sum [175 180 185 190 195]


In [52]:
print('row max',np.max(arr3, axis = 1))  # row max 
print('column max',np.max(arr3, axis  = 0))         # column max

row max [29 34 39 44 49]
column max [45 46 47 48 49]


In [62]:
# print(dir(np))

In [63]:
np.square(arr3)

array([[ 625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156],
       [1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936],
       [2025, 2116, 2209, 2304, 2401]])

In [ ]:
# Bitwise function in Numpy - bitwise_and,bitwise_or,bitwise_not, bitwise_xor, bitwise_repr()

In [64]:
arr11 = np.array([0,30,40,60,90])
arr11

array([ 0, 30, 40, 60, 90])

In [66]:
print(np.bitwise_and(np.array([[10,11],[12,13]]),np.array([[20,21],[22,23]])))

[[0 1]
 [4 5]]


In [80]:
11 & 21

1

In [68]:
print(np.bitwise_xor(np.array([[10,11],[12,13]]),np.array([[20,21],[22,23]])))

[[30 30]
 [26 26]]


In [96]:
int(bin(11)[2:]) & int(bin(21)[2:])

881

In [86]:
bin(20)

'0b10100'

In [87]:
bin(10)

'0b1010'

## Array indexing and slicing

In [98]:
arr12 = np.arange(25,50).reshape(5,5)
arr12

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [100]:
print(arr12[:,:])

[[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]


In [102]:
print(arr12[1][3])
print()
print(arr12[1,3])

33

33


In [103]:
print(arr12[1:3,:])

[[30 31 32 33 34]
 [35 36 37 38 39]]


In [104]:
print(arr12[:,2:3])

[[27]
 [32]
 [37]
 [42]
 [47]]


In [123]:
print(arr12[::2,2::2])

[[27 29]
 [37 39]
 [47 49]]


In [3]:
arr1 = np.arange(25,30)
arr1

array([25, 26, 27, 28, 29])

In [4]:
x= arr1[1],arr1[-1],arr1[2]
x

(26, 29, 27)

In [5]:
s = np.array([-1,2,0,3])
arr1[s]

array([29, 27, 25, 28])

In [7]:
arr2 = np.arange(100,130).reshape(6,5)
arr2

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129]])

In [10]:
r = np.array([-1,2,0,3])
c = np.array([-1,2,0,3])
arr2[r,c]

array([129, 112, 100, 118])

In [11]:
np.sum(arr2)

3435

In [12]:
np.sum(arr2<111) ## returns a count value of numbers less than 111

11

In [13]:
np.count_nonzero(arr2<105)

5

In [14]:
np.count_nonzero(arr2<105,axis=1) ## columns comparision

array([5, 0, 0, 0, 0, 0], dtype=int64)

In [15]:
np.count_nonzero(arr2<105,axis=0)  ## row comparision

array([1, 1, 1, 1, 1], dtype=int64)

# Structured array


In [21]:
emp_name = ['Ross','Cath','Berth','John']
emp_num = [1010,1011,1012,1013]
emp_sal = [10000.00, 18000.00, 21000.00, 16000.00]

In [23]:
emp_data = np.zeros(4,dtype = {'names':('name','id_num','sal'),'formats':('U10','i4','f8')})
emp_data

array([('', 0, 0.), ('', 0, 0.), ('', 0, 0.), ('', 0, 0.)],
      dtype=[('name', '<U10'), ('id_num', '<i4'), ('sal', '<f8')])

In [27]:
emp_data.dtype

dtype([('name', '<U10'), ('id_num', '<i4'), ('sal', '<f8')])

In [25]:
emp_data ['name'] = emp_name
emp_data['id_num'] = emp_num
emp_data['sal'] = emp_sal
emp_data

array([('Ross', 1010, 10000.), ('Cath', 1011, 18000.),
       ('Berth', 1012, 21000.), ('John', 1013, 16000.)],
      dtype=[('name', '<U10'), ('id_num', '<i4'), ('sal', '<f8')])

In [30]:
emp_data['name']

array(['Ross', 'Cath', 'Berth', 'John'], dtype='<U10')

# Array Broadcasting

In [4]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [5]:
a=10
arr1+a

array([10, 11, 12, 13, 14])

In [6]:
arr2 = np.arange(12).reshape(2,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [7]:
arr2+a

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21]])

In [8]:
arr3 = np.arange(25).reshape(5,5)
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
arr3+arr1

array([[ 0,  2,  4,  6,  8],
       [ 5,  7,  9, 11, 13],
       [10, 12, 14, 16, 18],
       [15, 17, 19, 21, 23],
       [20, 22, 24, 26, 28]])

In [10]:
arr3*arr1   # arr3 row element with arr1 all element

array([[ 0,  1,  4,  9, 16],
       [ 0,  6, 14, 24, 36],
       [ 0, 11, 24, 39, 56],
       [ 0, 16, 34, 54, 76],
       [ 0, 21, 44, 69, 96]])

In [40]:
arr1

array([0, 1, 2, 3, 4])

## Iterating over an array

In [11]:
arr1

array([0, 1, 2, 3, 4])

In [42]:
for i in arr1:
    print(i)

0
1
2
3
4


In [12]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
for i in arr3:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [14]:
arr3.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [15]:
for i in np.nditer(arr3,order = 'c'):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [47]:
for i in np.nditer(arr3,order = 'F'):
    print(i)

0
5
10
15
20
1
6
11
16
21
2
7
12
17
22
3
8
13
18
23
4
9
14
19
24


## Splitting an array



In [16]:
arr1 = np.arange(25)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
# splitting arr1 into 5 equal sizes
np.split(arr1,5)

[array([0, 1, 2, 3, 4]),
 array([5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14]),
 array([15, 16, 17, 18, 19]),
 array([20, 21, 22, 23, 24])]

In [18]:
# split array at specified position

np.split(arr1,[3,5,9,11,22])

[array([0, 1, 2]),
 array([3, 4]),
 array([5, 6, 7, 8]),
 array([ 9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]),
 array([22, 23, 24])]

In [19]:
arr2 = np.arange(25).reshape(5,5)
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [55]:
np.split(arr2,[2,3])

[array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

In [20]:
np.split(arr2,[2,3], axis=1)

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [21]:
np.hsplit(arr2,[2,3])

[array([[ 0,  1],
        [ 5,  6],
        [10, 11],
        [15, 16],
        [20, 21]]),
 array([[ 2],
        [ 7],
        [12],
        [17],
        [22]]),
 array([[ 3,  4],
        [ 8,  9],
        [13, 14],
        [18, 19],
        [23, 24]])]

In [22]:
np.vsplit(arr2,[3,2])

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 array([], shape=(0, 5), dtype=int32),
 array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])]

## View and Copy

In [23]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
v1 = arr1.view()
v1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [35]:
arr1[0] = 111
v1

array([111,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [28]:
arr2 = np.arange(5)
arr2

array([0, 1, 2, 3, 4])

In [30]:
a = arr2
a

array([0, 1, 2, 3, 4])

In [31]:
c = np.copy(arr2)
c

array([0, 1, 2, 3, 4])

In [32]:
arr2[0] = 111

In [33]:
print(a)
print(c)

[111   1   2   3   4]
[0 1 2 3 4]


## Stacking or concatenation

##### shape of the arrays should be same for stacking

In [38]:
arr1 = np.array([['A','B'],['C','D']])
arr2 = np.array([['Z','Y'],['W','X']])
print(arr1)
print(arr2)


[['A' 'B']
 ['C' 'D']]
[['Z' 'Y']
 ['W' 'X']]


In [40]:
np.concatenate((arr1,arr2))

array([['A', 'B'],
       ['C', 'D'],
       ['Z', 'Y'],
       ['W', 'X']], dtype='<U1')

In [41]:
np.concatenate((arr1,arr2),axis =1)

array([['A', 'B', 'Z', 'Y'],
       ['C', 'D', 'W', 'X']], dtype='<U1')